services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=cbthub_test
      - allowPublicKeyRetrieval=true